---

- name: install haproxy
  yum:
    name: haproxy
    state: latest
    update_cache: yes

- name: copy haproxy.cfg
  template: src=templates/haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg
  #template: src=templates/haproxy.cfg.j2 dest=/tmp/haproxy.cfg
  #delegate_to: localhost  # for debugging

- name: restart haproxy
  service:
    name: haproxy
    state: restarted

- name: start and enable haproxy
  service:
    name: haproxy
    state: started
    enabled: true
...
